import './globals.css'

import { Jost } from 'next/font/google'
//component import
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Link from 'next/link'

const jost = Jost({
  weight: ['200','300', '500'],
  style: ['normal', 'italic'],
  subsets: ['latin']
})

/* skiplink */


export const metadata = {
  title: 'AlphaRedux',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Link href={"#main_content"} className={"skip_to_main"} tabIndex={"0"} id='skipLink'>Skip To Main Content</Link>
        <Navbar/>
        
        {children}
        <Link href={"#skipLink"} className={"back_to_top"} tabIndex={"0"}>Back To Top</Link>

        <Footer/>
        </body>
    </html>
  )
}
