name: Continuous Integration

# triggered on PR to main
on:
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.0] # keep at 18.17.0 for nextjs

    steps:
    - uses: actions/checkout@v3
    - name: Setup node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
